inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - bin/bundle
  TargetRubyVersion:
    2.6

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 75
